---
platform: linux

inputs:
- name: bosh-disaster-recovery-acceptance-tests
- name: terraform-state
- name: director-creds
- name: jumpbox-creds
- name: stemcell

outputs:
- name: b-drats-integration-config

params:
  BOSH_SSH_USERNAME: jumpbox
  TIMEOUT_IN_MINUTES: 30
  BOSH_CLIENT: admin
  CREDHUB_CLIENT: credhub-admin
  CREDHUB_SERVER:
  INCLUDE_DEPLOYMENT_TESTCASE: true
  INCLUDE_TRUNCATE_DB_BLOBSTORE_TESTCASE: true
  INCLUDE_CREDHUB_TESTCASE: true

run:
  path: bosh-disaster-recovery-acceptance-tests/ci/tasks/generate-b-drats-integration-config/task.sh
