---
platform: linux

inputs:
- name: bosh-disaster-recovery-acceptance-tests
- name: bbr-binary-release
- name: b-drats-integration-config

params:
  INTEGRATION_CONFIG_PATH: integration_config.json
  BBR_BINARY: bbr-binary-release/bbr-[0-9]*-linux-amd64
  GINKGO_TIMEOUT: 24h0m0s

run:
  path: bosh-disaster-recovery-acceptance-tests/ci/tasks/run-b-drats/task.sh
