---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: bosh-disaster-recovery-acceptance-tests
- name: bbr-binary-release
- name: b-drats-integration-config
- name: jumpbox-creds

params:
  INTEGRATION_CONFIG_PATH: integration_config.json
  GINKGO_TIMEOUT: 24h0m0s

run:
  path: bosh-disaster-recovery-acceptance-tests/ci/tasks/run-b-drats/task.sh
