---
vault_creds: &vault_creds
  url: ((vault/server.url))
  role_id: ((vault/resource_credentials.role_id))
  secret_id: ((vault/resource_credentials.secret_id))

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
    tag: latest

- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

resources:
- name: cryogenics-ci
  type: git
  source:
    uri: git@github.com:pivotal/cryogenics-concourse-tasks.git
    private_key: ((github.ssh_key))
    branch: 182721080-toolsmiths-credhub-envvars

- name: smith-env
  type: pcf-pool
  source:
    api_token: ((toolsmiths.api_token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: us_2_13

- name: bosh-disaster-recovery-acceptance-tests-prs
  type: pull-request
  source:
    repository: cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests
    access_token: ((github.access_token))

- name: bbr-binary-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github.access_token))

- name: gcs-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-bionic-go_agent

jobs:
- name: claim-env
  plan:
  - get: bbr-binary-release
    trigger: true
  - get: bosh-disaster-recovery-acceptance-tests-prs
    trigger: true
  - put: smith-env
    params:
      action: claim

- name: run-b-drats-prs
  serial: true
  serial_groups: [prs]
  plan:
  - in_parallel:
    - get: smith-env
      passed: [claim-env]
      trigger: true
    - get: bosh-disaster-recovery-acceptance-tests-prs
      passed: [claim-env]
    - get: bbr-binary-release
      passed: [claim-env]
    - get: gcs-stemcell
    - get: cryogenics-ci
  - put: bosh-disaster-recovery-acceptance-tests-prs
    params:
      path: bosh-disaster-recovery-acceptance-tests-prs
      status: pending
      context: b-drats
  - task: alias-env
    file: cryogenics-ci/tasks/toolsmiths/bosh-envify/task.yml
    input_mapping:
      cryogenics-tasks: cryogenics-ci
      toolsmiths-env: smith-env
  - load_var: pooled-env
    file: bosh-env/metadata.yml
    format: yml
    # https://github.com/cloudfoundry/bosh-disaster-recovery-acceptance-tests/blob/552efea46339f782831fd3749c45d221c089a9b7/README.md#running-b-drats-locally
  - task: build-b-drats-integration-config
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: cryogenics/essentials-cf6 }
      inputs:
      - name: smith-env
      - name: gcs-stemcell
      outputs:
      - name: b-drats-integration-config
      run:
        path: /bin/bash
        args:
        - "-e"
        - "-c"
        - |
          cat > b-drats-integration-config/integration_config.yml << EOF
          bosh_ssh_private_key: |-
          $(echo "((.:pooled-env.BBR_PRIVATE_KEY))" | sed -E 's/(-+(BEGIN|END) RSA PRIVATE KEY-+) *| +/\1\n/g' |  sed 's/^/  /')
          bosh_ssh_username: "bbr"
          bosh_host: "((.:pooled-env.BOSH_ENVIRONMENT))"
          bosh_client: "((.:pooled-env.BOSH_CLIENT))"
          bosh_client_secret: "((.:pooled-env.BOSH_CLIENT_SECRET))"
          bosh_ca_cert: |-
          $(echo "((.:pooled-env.BOSH_CA_CERT))" | sed -E 's/(-+(BEGIN|END) CERTIFICATE-+) *| +/\1\n/g' | sed 's/^/  /')
          credhub_client: "((.:pooled-env.CREDHUB_CLIENT))"
          credhub_client_secret: "((.:pooled-env.CREDHUB_SECRET))"
          credhub_server: $(echo "((.:pooled-env.CREDHUB_SERVER))" | sed -E 's/(.*):.*/\1/g')
          credhub_ca_cert: |-
          $(echo "((.:pooled-env.CREDHUB_CA_CERT))" | sed -E 's/(-+(BEGIN|END) CERTIFICATE-+) *| +/\1\n/g' | sed 's/^/  /')
          timeout_in_minutes: 30
          stemcell_src: "$( cat gcs-stemcell/url )"
          include_credhub_testcase: true
          include_deployment_testcase: true
          include_truncate_db_blobstore_testcase: true
          deployment_vm_type: medium
          deployment_network: "((.:pooled-env.BOSH_ENV_NAME))-management-subnet"
          deployment_az: us-central1-f
          EOF
          cat b-drats-integration-config/integration_config.yml | yq '.' > b-drats-integration-config/integration_config.json
 
  - task: run-b-drats
    privileged: true
    file: bosh-disaster-recovery-acceptance-tests-prs/ci/tasks/run-b-drats/task.yml
    params:
      JUMPBOX_IP: ((.:pooled-env.INSTANCE_JUMPBOX_EXTERNAL_IP))
      JUMPBOX_PRIVATE_KEY: ((.:pooled-env.INSTANCE_JUMPBOX_PRIVATE))
      JUMPBOX_USER: ((.:pooled-env.INSTANCE_JUMPBOX_USER))
    input_mapping:
      bosh-disaster-recovery-acceptance-tests: bosh-disaster-recovery-acceptance-tests-prs
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
    on_success:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: success
        context: b-drats

- name: unclaim-env
  plan:
  - get: bosh-disaster-recovery-acceptance-tests-prs
    passed:
    - run-b-drats-prs
  - get: smith-env
    trigger: true
    passed:
    - run-b-drats-prs
  - put: smith-env
    params:
      action: unclaim
      env_file: smith-env/metadata

