#!/usr/bin/env bash
set -eu -o pipefail

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

BBR_BINARY_PATH="$(which true)"
INTEGRATION_CONFIG_PATH="${ROOT_DIR}/scripts/dry-run-config.json"

echo "> ginkgo run --dry-run..."
(
  set -eu -o pipefail
  cd "${ROOT_DIR}"

  export BBR_BINARY_PATH
  export INTEGRATION_CONFIG_PATH

  go run github.com/onsi/ginkgo/v2/ginkgo run --dry-run -r ./...
)
echo "^ ... DONE"

