#!/usr/bin/env bash
set -eu -o pipefail

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

(
  cd "${ROOT_DIR}"
  if ! command -v golangci-lint &> /dev/null; then
    echo "Installing golangci-lint@latest..."
    go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
  fi
)

PATH="$(go env GOPATH)/bin":${PATH}
export PATH

GOOS="linux"

echo "> GOOS=${GOOS} golangci-lint... (v$(golangci-lint version --short))"
golangci-lint run "${ROOT_DIR}"/...
echo "^ ... DONE"
