---
platform: linux

inputs:
- name: bosh-disaster-recovery-acceptance-tests
- name: jumpbox-creds
- name: jumpbox-deployment
- name: jumpbox-state
- name: terraform-state

outputs:
- name: jumpbox-creds
- name: jumpbox-state

params:
  ENVIRONMENT_NAME:
  GCP_SERVICE_ACCOUNT_KEY:
  BOSH_OPERATION: create-env # Set bosh command to run, e.g. create-env or delete-env

run:
  path: bosh-disaster-recovery-acceptance-tests/ci/tasks/jumpbox-operation/task.sh
